#!/bin/bash

sudo apt update

sudo apt install -y build-essential clang flex bison g++ gawk \
  gcc-multilib g++-multilib gettext git libssl-dev \
  rsync unzip zlib1g-dev file wget libglib2.0-dev \
  libncurses-dev python3-lib2to3 device-tree-compiler python3-pycryptodome python3-pyelftools

pip3 install pycryptodomex pyelftools

pip3 install pyusb usb crypto ecdsa crcmod tqdm pycryptodome

cp build/files ./openwrt/ -r

cd third_party/connectedhomeip

git submodule init
git submodule update third_party/pigweed \
  third_party/jsoncpp \
  third_party/nlassert \
  third_party/editline \
  third_party/nlunit-test \
  third_party/nlio \
  third_party/perfetto \
  third_party/libwebsockets

cd ../../openwrt
cp feeds.conf.default feeds.conf
echo src-link ezmesh $PWD/../package/RafaelMicro/EZMesh >>feeds.conf
echo src-link chip $PWD/../package/project-chip >>feeds.conf

./scripts/feeds update -a
./scripts/feeds install -a

cp ../config/def_config ./.config
make defconfig
